filegroup(
    name = 'android',
    srcs = ['android.build_defs'],
    visibility = ['PUBLIC'],
)

filegroup(
    name = 'native',
    srcs = ['native.build_defs'],
    visibility = ['PUBLIC'],
)

filegroup(
    name = 'appium',
    srcs = ['appium.build_defs'],
    visibility = ['PUBLIC'],
)
