go_binary(
    name = 'please_go_tool',
    srcs = ['main.go'],
    deps = [
        '//src/cli',
        '//third_party/go:logging',
        '//tools/please_go_tool/remote',
        '//tools/please_go_tool/testmain',
    ],
    visibility = ['PUBLIC'],
)
