subinclude('//android')

android_resource(
    name = 'resources',
    manifest = 'app/src/main/AndroidManifest.xml',
    package = 'com.example.android.asymmetricfingerprintdialog',
    res = 'app/src/main/res',
    resources_root = 'android/app/src/main',
)
